# NOURA EL KHOLTI

## Analyse en Composantes Principales (PCA)

L'Analyse en Composantes Principales (PCA) est une méthode statistique de réduction de dimensionnalité. Son objectif est de transformer des variables corrélées en un nouvel ensemble de variables non corrélées, appelées composantes principales. Ces composantes sont des combinaisons linéaires des variables originales, orientées dans les directions où la variance des données est maximale.

### 1. Les 4 Étapes Fondamentales

Le processus mathématique de la PCA se décompose en quatre étapes clés:

1. **Standardisation (Centrage et Réduction)**
   Il est crucial que toutes les variables contribuent de manière égale à l'analyse, indépendamment de leur échelle. On transforme chaque donnée $X$ pour obtenir une moyenne de 0 et un écart-type de 1.
$$Z = \frac{X - \mu}{\sigma}$$

2. **Calcul de la Matrice de Covariance**
   Cette étape permet de comprendre comment les variables de l'ensemble de données varient par rapport à la moyenne les unes des autres (corrélations).
$$\Sigma = \frac{1}{n-1} Z^T Z$$

3. **Décomposition Propre (Eigen-decomposition)**
   On calcule les vecteurs propres ($v$) et les valeurs propres ($\lambda$) de la matrice de covariance.
   - Les vecteurs propres définissent les nouvelles directions (axes).
   - Les valeurs propres déterminent l'importance (la variance expliquée) de chaque axe.
$$\Sigma v = \lambda v$$

4. **Projection**
   Enfin, on sélectionne les $k$ vecteurs propres associés aux plus grandes valeurs propres pour former une matrice de passage, et on projette les données originales dans ce nouvel espace de dimension réduite.

### 2. Préparation des Données

Nous analysons ici un échantillon de 7 véhicules selon trois critères : Puissance (cv), Poids (kg), et Consommation (L/100km).

In [ ]:
import numpy as np
import pandas as pd

# Dataset: Caractéristiques techniques de voitures
donnees = {
    'Puissance_cv': [110, 150, 200, 250, 300, 450, 600],
    'Poids_kg': [1200, 1350, 1500, 1650, 1800, 1950, 2100],
    'Consommation': [5.5, 6.8, 8.2, 9.5, 11.2, 14.5, 18.0]
}

df = pd.DataFrame(donnees)
X = df.values

# Affichage simple du tableau et de la matrice
print("--- DataFrame ---")
print(df)

print("\n--- Matrice X ---")
print(X)

```
--- DataFrame ---
   Puissance_cv  Poids_kg  Consommation
0           110      1200           5.5
1           150      1350           6.8
2           200      1500           8.2
3           250      1650           9.5
4           300      1800          11.2
5           450      1950          14.5
6           600      2100          18.0

--- Matrice X ---
[[ 110.  1200.     5.5]
 [ 150.  1350.     6.8]
 [ 200.  1500.     8.2]
 [ 250.  1650.     9.5]
 [ 300.  1800.    11.2]
 [ 450.  1950.    14.5]
 [ 600.  2100.    18. ]]
```

### 3. Implémentation du Moteur PCA

La fonction executer_pca automatise la réduction de dimension en quatre étapes clés:

In [ ]:
def executer_pca(X, n_comp=2):
    # 1. Standardisation
    X_std = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
    
    # 2. Matrice de Covariance
    mat_cov = np.cov(X_std.T)
    
    # 3. Vecteurs et Valeurs propres
    valeurs, vecteurs = np.linalg.eig(mat_cov)
    
    # Tri décroissant
    idx = np.argsort(valeurs)[::-1]
    valeurs, vecteurs = valeurs[idx], vecteurs[:, idx]
    
    # 4. Projection
    W = vecteurs[:, :n_comp]
    X_pca = X_std @ W
    
    return valeurs, X_pca

valeurs_propres, X_reduit = executer_pca(X)

### 4. Interprétation des Résultats

In [ ]:
# Affichage des résultats essentiels
print(f"Importance des axes (Valeurs propres):\n\t{valeurs_propres}")
print(f"Ancienne forme : {X.shape} -> Nouvelle forme: {X_reduit.shape}")

```
Importance des axes (Valeurs propres):
    [3.44506401e+00 5.47178262e-02 2.18158999e-04]
Ancienne forme : (7, 3) -> Nouvelle forme: (7, 2)
```

L'analyse des résultats numériques confirme que la réduction de dimension est une réussite. Le passage d'une forme $(7, 3)$ à $(7, 2)$ simplifie le jeu de données sans perte d'information majeure, car la première valeur propre ($3.445$) domine largement les autres. Cela prouve que les variables initiales sont fortement corrélées et que l'essentiel de la variance est capturé par les deux premières composantes principales, validant ainsi la pertinence de ce nouvel espace réduit pour l'étude des véhicules.